services:
  gitlab:
    image: "gitlab/gitlab-ee:${GITLAB_VERSION}-ee.0"
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      - '443:443'
      - '2424:22'
    volumes:
      - "${GITLAB_DIR}/config:/etc/gitlab"
      - "${GITLAB_DIR}/logs:/var/log/gitlab"
      - "${GITLAB_DIR}/data:/var/opt/gitlab"
    shm_size: '256m'
    network_mode: host
