services:

  server:
    container_name: auth-service
    build:
      context: "./${REPO_DIR_NAME}"
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
    depends_on:
      - db

  db:
      container_name: auth-service-postgres
      image: 'postgres:16'
      restart: always
      environment:
        POSTGRES_PORT: ${DB_PORT}
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
        - '${DB_PORT}:${DB_PORT}'